/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0aebb660fd640acbdcffffea0b879858)
interface __BaseEnv_Env {
	PR_ACTIONS: "opened,reopened,ready_for_review";
	NOTIFY_DRAFTS: "false";
	IGNORED_AUTHORS: "";
	SLACK_WEBHOOK_URL: string;
	GITHUB_WEBHOOK_SECRET: string;
	WATCHED_REPOS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PR_ACTIONS" | "NOTIFY_DRAFTS" | "IGNORED_AUTHORS" | "SLACK_WEBHOOK_URL" | "GITHUB_WEBHOOK_SECRET" | "WATCHED_REPOS">> {}
}
