/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0f822f886d86ecf81931f54b866bb6d3)
interface __BaseEnv_Env {
	PR_ACTIONS: "opened,reopened,ready_for_review";
	NOTIFY_DRAFTS: "false";
	IGNORED_AUTHORS: "";
	WATCHED_REPOS: ["onamfc/52-for-52","onamfc/laravel-devlogger","onamfc/gravity-forms-clevertap-integration","onamfc/laravel-database-archiver","onamfc/laravel-route-visualizer","onamfc/eloquent-to-json-generator","onamfc/mcp-starter-template-ts","onamfc/video-transcoder","onamfc/github-non-follow-backs","onamfc/api-mocker","onamfc/developer-log","onamfc/github-follow-back","onamfc/package-analyzer","onamfc/npm-vulnerability-scanner","onamfc/vibe-coder-prompt-builder","onamfc/rag-chat","onamfc/mcp-github-integration","onamfc/agent-prompt-library","onamfc/security-scanner","onamfc/cheesebox","onamfc/img-optimize","onamfc/case-shift","onamfc/waypointjs","onamfc/stadium-lights","onamfc/branch-clean","onamfc/magic-calculator","onamfc/gavel","onamfc/disc-drive","onamfc/drizzle-soft-delete","onamfc/runner-404","onamfc/exitramp","onamfc/linear-archive","LinkForty/core","LinkForty/mobile-sdk-react-native","LinkForty/mobile-sdk-ios","LinkForty/mobile-sdk-android","LinkForty/mobile-sdk-expo","LinkForty/fliq","LinkForty/mcp-server","LinkForty/aasa-validator","LinkForty/og-preview","xantus-ai/Fleet","xantus-ai/wp-llms-plugin","xantus-ai/spec-seal"];
	SLACK_WEBHOOK_URL: string;
	GITHUB_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PR_ACTIONS" | "NOTIFY_DRAFTS" | "IGNORED_AUTHORS" | "WATCHED_REPOS" | "SLACK_WEBHOOK_URL" | "GITHUB_WEBHOOK_SECRET">> {}
}
